platform :ios, '8.0'
use_frameworks!

workspace 'entree'
xcodeproj 'entree.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'

def appdeps
  pod 'Colours/Swift', '~> 5.12.0'
  pod 'Whisper', '~> 2.1'
end

def sdkdeps
   pod 'Alamofire', '~> 3.1.3'
   pod 'RealmSwift', '~> 0.98.2'
   pod 'DeviceKit', '~> 0.3.2'
   pod 'ReachabilitySwift', '~> 2.3.3'
   pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

def testdeps
  pod 'Quick', '~> 0.9.2'
  pod 'Nimble', '~> 4.0.0'
  pod 'Nocilla', '~> 0.10.0'
end

target :entree do
  xcodeproj 'entree.xcodeproj'
  sdkdeps
  appdeps
end

target :entreeSDK do
  xcodeproj 'entree.xcodeproj'
  sdkdeps
end

target :entreeTests do
  xcodeproj 'entree.xcodeproj'
  testdeps
end

target :entreeSDKTests do
  xcodeproj 'entree.xcodeproj'
  testdeps
end
